# Generated by Django 5.1.6 on 2025-03-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('province', models.CharField(db_column='Province', db_comment='省份、自治区、以及全国', max_length=10, primary_key=True, serialize=False)),
                ('year_2023', models.IntegerField(blank=True, db_comment='2023年末总人口数量', null=True)),
                ('year_2022', models.IntegerField(blank=True, db_comment='2022年末总人口数量', null=True)),
                ('year_2021', models.IntegerField(blank=True, db_comment='2021年末总人口数量', null=True)),
                ('year_2020', models.IntegerField(blank=True, db_comment='2020年末总人口数量', null=True)),
            ],
            options={
                'db_table': 'population',
                'managed': False,
            },
        ),
    ]
