# Generated by Django 5.1.6 on 2025-03-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Populations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('省份', models.CharField(blank=True, max_length=50, null=True)),
                ('number_2023年', models.IntegerField(blank=True, db_column='2023年', null=True)),
                ('number_2022年', models.IntegerField(blank=True, db_column='2022年', null=True)),
                ('number_2021年', models.IntegerField(blank=True, db_column='2021年', null=True)),
                ('number_2020年', models.IntegerField(blank=True, db_column='2020年', null=True)),
                ('number_2019年', models.IntegerField(blank=True, db_column='2019年', null=True)),
                ('number_2018年', models.IntegerField(blank=True, db_column='2018年', null=True)),
                ('number_2017年', models.IntegerField(blank=True, db_column='2017年', null=True)),
                ('number_2016年', models.IntegerField(blank=True, db_column='2016年', null=True)),
                ('number_2015年', models.IntegerField(blank=True, db_column='2015年', null=True)),
                ('number_2014年', models.IntegerField(blank=True, db_column='2014年', null=True)),
                ('number_2013年', models.IntegerField(blank=True, db_column='2013年', null=True)),
                ('number_2012年', models.IntegerField(blank=True, db_column='2012年', null=True)),
                ('number_2011年', models.IntegerField(blank=True, db_column='2011年', null=True)),
                ('number_2010年', models.IntegerField(blank=True, db_column='2010年', null=True)),
                ('number_2009年', models.IntegerField(blank=True, db_column='2009年', null=True)),
                ('number_2008年', models.IntegerField(blank=True, db_column='2008年', null=True)),
                ('number_2007年', models.IntegerField(blank=True, db_column='2007年', null=True)),
                ('number_2006年', models.IntegerField(blank=True, db_column='2006年', null=True)),
                ('number_2005年', models.IntegerField(blank=True, db_column='2005年', null=True)),
            ],
            options={
                'db_table': 'populations',
                'managed': False,
            },
        ),
    ]
